# Terraform az boilerplate
version: '3'

dotenv: ['.env']

includes:
  tf: 
    taskfile: .tasks/TerraformTasks.yml
    aliases : [terraform]
  docs: .tasks/DocsTasks.yml
  costs: .tasks/CostsTasks.yml
  security: .tasks/SecurityTasks.yml
  install: .tasks/InstallTasks.yml

tasks:
  default:
     desc: List all tasks
     cmds:
       - task --list-all
