# Terraform az boilerplate
version: '3'

dotenv: ['.env']

includes:
  tf: .tasks/TerraformTasks.yml
  docs: .tasks/DocsTasks.yml
  costs: .tasks/CostsTasks.yml
  security: .tasks/SecurityTasks.yml
  install: .tasks/InstallTasks.yml
  app: .tasks/AppTasks.yml

tasks:
  default:
     desc: List all tasks
     cmds:
       - task --list-all
