# Terraform az boilerplate
version: '3'

dotenv: ['.env']

includes:
  tf: 
    taskfile: .tasks/TerraformTasks.yml
    aliases : [terraform]
  docs: .tasks/DocsTasks.yml
  costs: .tasks/CostsTasks.yml
  security: .tasks/SecurityTasks.yml

tasks:
  default:
     desc: List all tasks
     cmds:
       - task --list-all
  required-tools:
    desc: Required tools
    cmds:
      - echo '🚀 Please install terraform, terraform-docs, tflint binaries before use with Chocolatey or Winget'