# Terraform az boilerplate

version: '3'

includes:
  terraform: tasks/TerraformTasks.yml
  tflint: tasks/TflintTasks.yml
  docs: tasks/TerraformDocsTasks.yml
  infracosts: tasks/InfraCostsTasks.yml
  checkov: tasks/CheckovTasks.yml

tasks:
  install-required-tools:
    desc: Describe required tools
    cmds:
      - echo 'Please install terraform, terraform-docs, tflint binaries before use with Chocolatey or Winget'