# Terraform az boilerplate

version: '3'

includes:
  terraform: .tasks/TerraformTasks.yml
  docs: .tasks/TerraformDocsTasks.yml
  infracosts: .tasks/InfraCostsTasks.yml
  checkov: .tasks/CheckovTasks.yml

tasks:
  default:
     desc: List all tasks
     cmds:
       - task --list-all
  required-tools:
    desc: Required tools
    cmds:
      - echo '🚀 Please install terraform, terraform-docs, tflint binaries before use with Chocolatey or Winget'